{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}
{% set release = '.'.join(version.split('.')[:2]) %}

package:
  name: q2-gneiss
  version: {{ version }}

source:
  path: ../..

build:
  script: python setup.py install

requirements:
  build:
    - python 3.5*
    - setuptools

  run:
    - python 3.5*
    - setuptools
    - gneiss >=0.3.0
    - scikit-bio
    - numpy
    - statsmodels  # TODO: fix this upstream
    - pandas
    - seaborn
    - bokeh
    - biom-format >=2.1.5,<2.2.0
    - qiime2 {{ release }}.*
    - q2-types {{ release }}.*

test:
  imports:
    - q2_gneiss
    - qiime2.plugins.gneiss

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
