{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2-gneiss
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - gneiss >=0.3.0
    - scikit-bio {{ scikit_bio }}
    # TODO: This numpy pin should probably be in the gneiss package, rather
    # than in q2-gneiss
    - numpy >=1.15.3
    - statsmodels >=0.9.0  # TODO: fix this upstream
    - pandas {{ pandas }}
    - seaborn
    - bokeh
    - biom-format {{ biom_format }}
    - qiime2 {{ qiime2_epoch }}.*
    - q2-types {{ qiime2_epoch }}.*

test:
  requires:
    - qiime2 >={{ qiime2 }}
    - q2-types >={{ q2_types }}
    - pytest

  imports:
    - q2_gneiss
    - qiime2.plugins.gneiss

  commands:
    - py.test --pyargs q2_gneiss

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
